### ISSUE TITLE
Would you like to use BirdPad for the Notepad parody?

### ISSUE THREAD

**Issue by PPPDUD** [Viswas-Programs/ParodyWindows11#1]
I have made a program in Python called BirdPad, and it's a direct competitor to Notepad. If you'd like, I can give you the source code so that you can use it instead of your current Notepad parody.

**Comment by Viswas-Programs** [comment]
Hi there, to whoever you are. 
If you want your app to be in this DE, You can submit it to my appstore, that is also here (Refer wiki in github)
For more easier communications, Discord is preffered. If you have one, please contact me there.

**Comment by Viswas-Programs** [comment]
Ok so I reviewed your BirdPad and it seems it's not even a python app, and this DE is primarily made in Python. 
Soo if you do happen to have a python version,  please link that. You can contact me in discord with this id
id: heheboi420

**Comment by PPPDUD** [comment]
It is a Python app, but it's closed source. I'll give you the source if
you'd like, but you'll need to keep it under wraps.

**Comment by Viswas-Programs** [comment]
Yes, but the final version can have obfuscated code, and you'd also have to make a separate python installer that would run in my software store in here.
You just link an installer for your app, and that installer has the stuff you need to do, you can download up obfucscated code.
HOWEVER:
The way my DE launches an app, is complicated. It doesnt startup the file as is. Rather, it imports the file customly using exec()​ and runs the main()​ function.
So what you have to tune in your app would be having a main function, and have it accept the 2 parameters that would be given at the start:
-username (string)
-notification (Class Notification). This is used to push notifications from any app to the DE, so whenever needed.
________________________________

**Comment by Viswas-Programs** [comment]
@PPPDUD You there?

**Comment by PPPDUD** [comment]
Yep, just took a bit to consider. No offense, but I think I'll retract my
offer.
